
# ckpt_path: out_qwen2p5vl_dentex_qlora/checkpoint-100
model_name: Qwen/Qwen2.5-VL-3B-Instruct
max_new_tokens: 256

train_jsonl: data/train_jsons/train.jsonl
val_jsonl: data/train_jsons/train.jsonl
classes: ["Missing teeth"]
prompt_name: prompt_qwen

output_dir: data/checkpoints

training:
  lora_rank: 16
  lora_scale: 2
  learning_rate: 2e-4 # 5e-5, 1e-4
  num_train_epochs: 5
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 32
  img_res1: 1380
  img_res2: 1380
  loss_masking: True
  embeddings_grad: False
  eval_steps: 50
  save_ckpt_steps: 50